### ISSUE TITLE
rankings are not sorted by both score and honor fields

### ISSUE THREAD

**Issue by lyninx** [alerobertson/aetherbot_Discord#2]
<img width="572" alt="screen shot 2018-12-10 at 12 10 34 pm" src="https://user-images.githubusercontent.com/8812109/49748784-ae91d980-fc74-11e8-9ecb-d85b18a2c522.png">
in this example, i have the same score as Crashboi, and although my honor score is higher, i appear lower in the list.

it would be nice to have the output be sorted by both fields.

**Comment by alerobertson** [comment]
All fixed up! Thanks for pointing it out.
